# TCL File Generated by Component Editor 8.0
# Sun Sep 27 00:05:52 COT 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SRAM_512KB_16b "SRAM 512KB - 16bits per record" v1.0
# | Jairo Andres Velasco 2009.09.27.00:05:52
# | Interfaz de memoria SRAM para la DE1
# | 
# +-----------------------------------


# +-----------------------------------
# | module SRAM_512KB_16b
# | 
set_module_property DESCRIPTION "Interfaz de memoria SRAM para la DE1"
set_module_property NAME SRAM_512KB_16b
set_module_property VERSION 1.0
set_module_property GROUP "Memories and Memory Controllers/SRAM"
set_module_property AUTHOR "Jairo Andres Velasco"
set_module_property DISPLAY_NAME "SRAM 512KB - 16bits per record"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE false
set_module_property SIMULATION_MODEL_IN_VERILOG false
set_module_property SIMULATION_MODEL_IN_VHDL false
set_module_property SIMULATION_MODEL_HAS_TULIPS false
set_module_property SIMULATION_MODEL_IS_OBFUSCATED false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_tristate_slave
# | 
add_interface avalon_tristate_slave avalon_tristate end
set_interface_property avalon_tristate_slave holdTime 0
set_interface_property avalon_tristate_slave minimumUninterruptedRunLength 1
set_interface_property avalon_tristate_slave bridgesToMaster ""
set_interface_property avalon_tristate_slave isMemoryDevice false
set_interface_property avalon_tristate_slave activeCSThroughReadLatency false
set_interface_property avalon_tristate_slave addressSpan 524288
set_interface_property avalon_tristate_slave setupTime 0
set_interface_property avalon_tristate_slave timingUnits Cycles
set_interface_property avalon_tristate_slave writeWaitTime 0
set_interface_property avalon_tristate_slave isNonVolatileStorage false
set_interface_property avalon_tristate_slave maximumPendingReadTransactions 0
set_interface_property avalon_tristate_slave readWaitTime 1
set_interface_property avalon_tristate_slave readLatency 0
set_interface_property avalon_tristate_slave printableDevice false

set_interface_property avalon_tristate_slave ASSOCIATED_CLOCK clock_sink

add_interface_port avalon_tristate_slave addr address Input 18
add_interface_port avalon_tristate_slave data data Bidir 16
add_interface_port avalon_tristate_slave we write_n Input 1
add_interface_port avalon_tristate_slave oe outputenable_n Input 1
add_interface_port avalon_tristate_slave ce chipselect_n Input 1
add_interface_port avalon_tristate_slave be byteenable_n Input 2

set_interface_assignment avalon_tristate_slave isMemoryDevice true
set_interface_property avalon_tristate_slave isMemoryDevice true

# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_sink
# | 
add_interface clock_sink clock end
set_interface_property clock_sink ptfSchematicName ""

add_interface_port clock_sink clk clk Input 1
# | 
# +-----------------------------------
